### ISSUE TITLE
Is it possible to provide the result of the model?

### ISSUE THREAD

**Issue by marco-hmc** [Ighina/MultiModalSA#1]
Is it possible to provide the result of the model?
So I can compare it with mine.
Thanks.

**Comment by Ighina** [comment]
Sure, which models specifically? I include a table with some results I collected for different configurations using this repository.
![results_edinburgh](https://user-images.githubusercontent.com/45108036/206059348-26d53251-c2e5-46f3-ad25-f6ce8def7f1d.png)

**Comment by marco-hmc** [comment]
Sorry for late reply. This is all I need already.
