### ISSUE TITLE
What are the environmental requirements

### ISSUE THREAD

**Issue by Shadow-zbw** [Ighina/MultiModalSA#2]

**Comment by Ighina** [comment]
For what I remember you should need just pytorch, numpy and pandas as extra libraries. You might want to check out the official MOSI github page for the requirements they provided. Also consider that this repository was created in 2020, so the versions of the libraries I used at the time are quite old. Anyway, I will add a requirements file soon

**Comment by Shadow-zbw** [comment]
By the way, the training of Transfomer models cannot be used.

**Comment by Shadow-zbw** [comment]
By the way, the training of Transformer models cannot be used

**Comment by Ighina** [comment]
If you want you can open another issue and explain what seems not to work
